-- Schéma initial complet, compatible H2 et PostgreSQL. Catalogue vide.
CREATE TABLE products (
    id          VARCHAR(64)    NOT NULL,
    name        VARCHAR(200)   NOT NULL,
    description VARCHAR(2000)  NOT NULL,
    price       DECIMAL(10, 2) NOT NULL,
    available   BOOLEAN        NOT NULL DEFAULT TRUE,
    stock       INT            NOT NULL DEFAULT 0,
    image_data  BYTEA          NULL,
    image_content_type VARCHAR(100) NULL,
    created_at  TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_products PRIMARY KEY (id)
);

-- Le premier administrateur est créé au démarrage par AdminUserSeeder,
-- avec CAWL_ADMIN_USERNAME / CAWL_ADMIN_PASSWORD et un hash BCrypt.
-- Aucun identifiant secret n'est inscrit dans cette migration.
CREATE TABLE admin_users (
    id            BIGINT         GENERATED BY DEFAULT AS IDENTITY,
    username      VARCHAR(100)   NOT NULL,
    password_hash VARCHAR(200)   NOT NULL,
    enabled       BOOLEAN        NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_admin_users PRIMARY KEY (id),
    CONSTRAINT uq_admin_users_username UNIQUE (username)
);


