-- Commandes clients et traçabilité des paiements CAWL.
-- Compatible H2 et PostgreSQL, comme la migration initiale.

CREATE TABLE orders (
    id                  BIGINT         GENERATED BY DEFAULT AS IDENTITY,
    reference           VARCHAR(30)    NOT NULL,
    status              VARCHAR(30)    NOT NULL,

    customer_first_name VARCHAR(100)   NOT NULL,
    customer_last_name  VARCHAR(100)   NOT NULL,
    customer_email      VARCHAR(200)   NOT NULL,
    customer_phone      VARCHAR(30)    NULL,

    delivery_method     VARCHAR(20)    NOT NULL,
    shipping_street     VARCHAR(200)   NULL,
    shipping_complement VARCHAR(200)   NULL,
    shipping_postal_code VARCHAR(20)   NULL,
    shipping_city       VARCHAR(100)   NULL,
    shipping_country    VARCHAR(2)     NULL,

    items_total         DECIMAL(10, 2) NOT NULL,
    shipping_fee        DECIMAL(10, 2) NOT NULL,
    total_amount        DECIMAL(10, 2) NOT NULL,
    currency            VARCHAR(3)     NOT NULL,

    -- Traces du prestataire de paiement (jamais de données de carte).
    hosted_checkout_id  VARCHAR(100)   NULL,
    payment_id          VARCHAR(100)   NULL,
    payment_status      VARCHAR(40)    NULL,
    paid_at             TIMESTAMP      NULL,

    created_at          TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_orders PRIMARY KEY (id),
    CONSTRAINT uq_orders_reference UNIQUE (reference)
);

CREATE INDEX idx_orders_created_at ON orders (created_at);

-- Le prix et le libellé sont recopiés à la commande : une évolution du catalogue
-- ne doit jamais modifier une commande déjà passée.
CREATE TABLE order_lines (
    id           BIGINT         GENERATED BY DEFAULT AS IDENTITY,
    order_id     BIGINT         NOT NULL,
    product_id   VARCHAR(64)    NOT NULL,
    product_name VARCHAR(200)   NOT NULL,
    unit_price   DECIMAL(10, 2) NOT NULL,
    quantity     INT            NOT NULL,
    line_total   DECIMAL(10, 2) NOT NULL,
    CONSTRAINT pk_order_lines PRIMARY KEY (id),
    CONSTRAINT fk_order_lines_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE
);

CREATE INDEX idx_order_lines_order ON order_lines (order_id);

-- Journal des notifications CAWL déjà traitées : garantit l'idempotence du webhook
-- (le prestataire peut rejouer un même événement plusieurs fois).
CREATE TABLE payment_events (
    event_id        VARCHAR(100) NOT NULL,
    event_type      VARCHAR(60)  NULL,
    order_reference VARCHAR(30)  NULL,
    received_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_payment_events PRIMARY KEY (event_id)
);

