-- Table des comptes d'administration (back-office /admin).
-- Aucun mot de passe en clair : password_hash contient un hash BCrypt.
CREATE TABLE admin_users (
    id            BIGINT         GENERATED BY DEFAULT AS IDENTITY,
    username      VARCHAR(100)   NOT NULL,
    password_hash VARCHAR(200)   NOT NULL,
    enabled       BOOLEAN        NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_admin_users PRIMARY KEY (id),
    CONSTRAINT uq_admin_users_username UNIQUE (username)
);

